-- ── Services table ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS services (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(150)  NOT NULL,
    slug        VARCHAR(150)  NOT NULL UNIQUE,
    tagline     VARCHAR(255)  DEFAULT NULL,
    description TEXT          DEFAULT NULL,
    icon        VARCHAR(60)   DEFAULT 'star',
    image       VARCHAR(255)  DEFAULT NULL,
    features    TEXT          DEFAULT NULL,
    price_label VARCHAR(80)   DEFAULT NULL,
    cta_text    VARCHAR(80)   DEFAULT 'Learn More',
    cta_url     VARCHAR(255)  DEFAULT NULL,
    is_featured TINYINT(1)    NOT NULL DEFAULT 0,
    sort_order  INT UNSIGNED  NOT NULL DEFAULT 0,
    status      ENUM('active','inactive') NOT NULL DEFAULT 'active',
    created_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Seed data ────────────────────────────────────────────────────
INSERT INTO services (title, slug, tagline, description, icon, features, price_label, cta_text, is_featured, sort_order, status) VALUES

('Personal Shopping',
 'personal-shopping',
 'Your dedicated style advisor',
 'Our personal shopping service pairs you with a dedicated Dakari style advisor who learns your taste, lifestyle, and budget — then hand-picks products from our catalogue just for you. Ideal for busy professionals who want premium quality without the scroll.',
 'shopping_bag',
 'One-on-one style consultation\nCurated product shortlist delivered to your inbox\nPriority access to new arrivals\nFree returns on first order\n24-hour response guarantee',
 'Free with any purchase',
 'Book a Consultation',
 1, 1, 'active'),

('Corporate Gifting',
 'corporate-gifting',
 'Premium gifts for teams & clients',
 'Make a lasting impression with bespoke corporate gifts. From branded packaging to bulk orders for hundreds of recipients, our corporate gifting team handles everything — sourcing, personalisation, and delivery — so you can focus on your business.',
 'briefcase',
 'Minimum order 10 units\nCustom branding & packaging available\nDedicated account manager\nBulk pricing discounts from 15%\nFlexible delivery scheduling\nInvoice & LPO accepted',
 'From KES 1,500 / unit',
 'Request a Quote',
 1, 2, 'active'),

('Gift Wrapping & Presentation',
 'gift-wrapping',
 'Packaging as premium as what is inside',
 'Every order deserves a beautiful entrance. Our signature gift wrapping service uses premium kraft paper, satin ribbon, and handwritten cards to transform any purchase into an unforgettable gift experience.',
 'gift',
 'Signature Dakari kraft wrap\nSatin ribbon in gold or green\nHandwritten personalised card\nSame-day wrapping for in-store orders\nCompostable materials',
 'From KES 250 per item',
 'Add to Order',
 1, 3, 'active'),

('Express Delivery',
 'express-delivery',
 'Nairobi same-day, Kenya next-day',
 'Need it now? Our express delivery network covers Nairobi CBD and key suburbs same-day, with next-day delivery to major towns across Kenya. All express parcels are tracked in real time and handled by our vetted delivery partners.',
 'truck',
 'Same-day delivery in Nairobi (order before 10am)\nNext-day to Mombasa, Kisumu, Nakuru & Eldoret\nReal-time SMS tracking updates\nSignature-on-delivery confirmation\nInsured parcels up to KES 50,000',
 'From KES 350',
 'Learn More',
 1, 4, 'active'),

('Product Customisation',
 'product-customisation',
 'Make it uniquely yours',
 'Stand out with personalised products. We offer engraving, embossing, monogramming, and custom colour options on select items. Perfect for anniversaries, graduations, and corporate milestones that deserve something truly one-of-a-kind.',
 'settings',
 'Engraving & embossing on leather goods\nMonogramming on selected accessories\nCustom colour options on select products\n5–7 business day turnaround\nFree design preview before production',
 'From KES 500 per item',
 'Explore Options',
 0, 5, 'active'),

('After-Sales Support',
 'after-sales-support',
 'We are here long after the purchase',
 'Our relationship does not end at checkout. Dakari\'s after-sales team is available to assist with warranties, product care, exchanges, and repairs. We stand behind every item we sell — and we stand behind our customers.',
 'shield',
 '14-day hassle-free returns\nWarranty claim assistance\nProduct care guidance & tutorials\nPriority support for repeat customers\nDedicated WhatsApp support line',
 'Included with all purchases',
 'Contact Support',
 0, 6, 'active');
